routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('frontend_root');

Route::group(['prefix' => 'ql'], function() {
	Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
	//
	Route::post('login', 'Auth\LoginController@login');
});

Route::group(['prefix' => 'ql', 'middleware' => 'auth'], function() {
	
	Route::get('/', 'Admin\AccountController@index')->name('admin_default_root');
	//
	Route::get('logout', 'Auth\LoginController@logout')->name('logout');
	// admin managemening users
	Route::resource('accounts', 'Admin\AccountController');
	// partner
	Route::get('partners/clear_cache', 'Admin\PartnerController@clear_cache')->name('partners.clear_cache');

	Route::resource('partners', 'Admin\PartnerController');

	Route::get('categories/clear_cache', 'Admin\CategoryController@clear_cache')->name('categories.clear_cache');

	Route::resource('categories', 'Admin\CategoryController');
	//
	Route::resource('products', 'Admin\ProductController');

	Route::resource('pages', 'Admin\PageController');

	Route::resource('posts', 'Admin\PostController');

	Route::get('ads/clear_cache', 'Admin\AdController@clear_cache')->name('ads.clear_cache');

	Route::resource('ads', 'Admin\AdController');
	
	Route::get('slides/clear_cache', 'Admin\SlideController@clear_cache')->name('slides.clear_cache');

	Route::resource('slides', 'Admin\SlideController');

	Route::get('setting', 'Admin\SettingController@index')->name('setting.index');

	Route::get('setting/clear_cache', 'Admin\SettingController@clear_cache')->name('setting.clear_cache');

	Route::post('setting', 'Admin\SettingController@store');

	Route::get('inquiry/index', 'Admin\InquiryController@index')->name('inquiry.index');

	Route::post('caches/clear_cache', 'Admin\CacheManagementController@clear_cache')->name('caches.clear_cache');

	Route::get('caches/index', 'Admin\CacheManagementController@index')->name('caches.index');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/product-category/{slug?}', 'FrontendController@category')->name('category_home');

Route::get('/product/{slug}', 'FrontendController@product')->name('product_home');

Route::get('/post-category/{slug}', 'FrontendController@pCategory')->name('post_category_home');

Route::get('/news/{slug}', 'FrontendController@postDetail')->name('post_detail_home');

Route::get('/pages/{slug}', 'FrontendController@pageDetail')->name('page_detail_home');

Route::get('/inquiry', 'FrontendController@getInquiry')->name('get_inquiry');

Route::post('/inquiry', 'FrontendController@postInquiry')->name('post_inquiry');

 Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });

app/Slide.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slide extends Model
{
	protected $fillable = [
        'title', 'description', 'type', 'url'
    ];

    public function rules($id = null) {
        return [
            'slide.title' => 'required|max:100|unique:slides,title,'. $id,
            'slide.url' => 'image|max:1024' .  (is_null($id) ? '|required' : ''),
            'slide.description' => 'max:150',
            'slide.type' => 'required'
        ];
    }
}

app/Http/Controllers/Admin/SlideController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Slide;
use App\Service\UploadImage;

class SlideController extends Controller
{
    use UploadImage;

    protected $slide;

    public function __construct(Slide $slide) {
        $this->slide = $slide;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $slides = Slide::orderBy('type')->get();

        return view('admin.slides.index', compact('slides'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.slides.create', ['slide' => $this->slide]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate($this->slide->rules());
        // process store image
        $name = $this->storeImage($request->file('slide.url'), 'slide');
        Slide::create([
            'title' => $request->input('slide.title'),
            'url' => $name,
            'description' => $request->input('slide.description'),
            'type' => $request->input('slide.type')
        ]);
        return redirect()->route('slides.index')->with('alert-success','slide was created success!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $slide = Slide::find($id);
        return view('admin.slides.edit', compact('slide'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate($this->slide->rules($id));
        $slide = Slide::find($id);
        // process store image
        if( $request->hasFile('slide.url')) {
            $this->deleteImage($slide->url);
            $slide->url = $this->storeImage($request->file('slide.url'), 'slide');
        }
        //
        $slide->title = $request->input('slide.title');
        $slide->description = $request->input('slide.description');
        $slide->type = $request->input('slide.type');
        $slide->save();
        //
        return redirect()->route('slides.index')->with('alert-success','slide was updated success!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slide = Slide::find($id);
        $this->deleteImage($slide->url);
        $slide->delete();
        
        return redirect()->route('slides.index')->with('alert-success','slide was deleted success!');
    }

    public function clear_cache() {
        allSlides('top', true);
        allSlides('bottom', true);
        return redirect()->route('slides.index')->with('alert-success','Clear cache was created success!');
    }
}

resources/views/admin/slides/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Create Slide</h3>
            </div>
            <!-- /.box-header -->
            @include('admin.slides.form')
        </div>
    </div>
</div>
@endsection

resources/views/admin/slides/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Edit slide</h3>
            </div>
            <!-- /.box-header -->
            @include('admin.slides.form')
        </div>
    </div>
</div>
@endsection

resources/views/admin/slides/form.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@php($url = is_null($slide->id) ? route('slides.store') : route('slides.update', $slide->id))
<form method="post" action="{{ $url }}" class="form-horizontal" enctype="multipart/form-data">
    <div class="box-body no-padding">
        @csrf
        @if(!is_null($slide->id))
            @method('PATCH')
        @endif
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Title</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="slide[title]" value="{{ $slide->title }}"/>
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">URL</label>
            <div class="col-sm-10">
                <p>Slide TOP: 602x300 px, slide BOTTOM: 182x132px</p>
                @if (!empty($slide->url))
                <img src="{{ asset($slide->url) }}" height="100px" width="100px"/>
                @endif
                <input type="file" class="form-control" name="slide[url]" accept="image/*"/>
            </div>
        </div>

        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Type</label>
            <div class="col-sm-4">
                <select name="slide[type]" class="form-control">
                    <option value="top" {{ $slide->type == 'top' ? 'selected="selected"' : '' }}>Top</option>
                    <option value="bottom" {{ $slide->type == 'bottom' ? 'selected="selected"' : '' }}>Bottom</option>
                </select>
            </div>
            <div class="col-sm-6">
                <span> TOP: 602x300 px</span>
                <br/>
                <span> BOTTOM: 182x132px</span>
            </div>
        </div>

        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Description</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="slide[description]" value="{{ $slide->description }}"/>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <a href="{{ route('slides.index') }}" class="btn btn-primary pull-left">Cancel</a>
        <button type="submit" class="btn btn-primary pull-right">{{ is_null($slide->id) ? 'Create' : 'Update' }}</button>
    </div>
</form>

resources/views/admin/slides/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
   <div class="col-xs-12">
      <div class="box">
         <div class="box-header">
            <h3 class="box-title">Danh sach Slides</h3>
            <div class="box-tools">
               <div class="input-group input-group-sm">
                  <a class="label label-success" href="{{route('slides.create')}}">New</a>
                  <a class="label label-success" href="{{ route('slides.clear_cache') }}">Clear Cache</a>
               </div>
            </div>
         </div>
         <!-- /.box-header -->
         <div class="box-body table-responsive no-padding">
            @if (empty($slides))
                Khong co slide nao!
            @else
                <table class="table table-hover">
                   <tbody>
                      <tr>
                         <th>ID</th>
                         <th>Title</th>
                         <th>URL</th>
                         <th>Description</th>
                         <th>Type</th>
                         <th></th>
                         <th></th>
                      </tr>
                      @foreach($slides as $slide)
                      <tr>
                         <td>{{ $slide->id }}</td>
                         <td>{{ $slide->title }}</td>
                         <td>
                          <img src="{{ asset($slide->url) }}" width="200px"/>
                         </td>
                         <td>{{ $slide->description }}</td>
                         <td>{{ $slide->type }}</td>
                         <td>
                             <a class="label label-primary" href="{{ route('slides.edit', $slide->id) }}">Edit</a>
                         </td>
                         <td>
                             <form action="{{ route('slides.destroy', $slide->id) }}" method="post" class="confirmDeleteRecord">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="label label-danger">Delete</button>
                             </form>
                         </td>
                      </tr>
                      @endforeach
                   </tbody>
                </table>
            @endif
         </div>
         <!-- /.box-body -->
      </div>
      <!-- /.box -->
   </div>
</div>
@endsection