routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('frontend_root');

Route::group(['prefix' => 'ql'], function() {
	Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
	//
	Route::post('login', 'Auth\LoginController@login');
});

Route::group(['prefix' => 'ql', 'middleware' => 'auth'], function() {
	
	Route::get('/', 'Admin\AccountController@index')->name('admin_default_root');
	//
	Route::get('logout', 'Auth\LoginController@logout')->name('logout');
	// admin managemening users
	Route::resource('accounts', 'Admin\AccountController');
	// partner
	Route::get('partners/clear_cache', 'Admin\PartnerController@clear_cache')->name('partners.clear_cache');

	Route::resource('partners', 'Admin\PartnerController');

	Route::get('categories/clear_cache', 'Admin\CategoryController@clear_cache')->name('categories.clear_cache');

	Route::resource('categories', 'Admin\CategoryController');
	//
	Route::resource('products', 'Admin\ProductController');

	Route::resource('pages', 'Admin\PageController');

	Route::resource('posts', 'Admin\PostController');

	Route::get('ads/clear_cache', 'Admin\AdController@clear_cache')->name('ads.clear_cache');

	Route::resource('ads', 'Admin\AdController');
	
	Route::get('slides/clear_cache', 'Admin\SlideController@clear_cache')->name('slides.clear_cache');

	Route::resource('slides', 'Admin\SlideController');

	Route::get('setting', 'Admin\SettingController@index')->name('setting.index');

	Route::get('setting/clear_cache', 'Admin\SettingController@clear_cache')->name('setting.clear_cache');

	Route::post('setting', 'Admin\SettingController@store');

	Route::get('inquiry/index', 'Admin\InquiryController@index')->name('inquiry.index');

	Route::post('caches/clear_cache', 'Admin\CacheManagementController@clear_cache')->name('caches.clear_cache');

	Route::get('caches/index', 'Admin\CacheManagementController@index')->name('caches.index');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/product-category/{slug?}', 'FrontendController@category')->name('category_home');

Route::get('/product/{slug}', 'FrontendController@product')->name('product_home');

Route::get('/post-category/{slug}', 'FrontendController@pCategory')->name('post_category_home');

Route::get('/news/{slug}', 'FrontendController@postDetail')->name('post_detail_home');

Route::get('/pages/{slug}', 'FrontendController@pageDetail')->name('page_detail_home');

Route::get('/inquiry', 'FrontendController@getInquiry')->name('get_inquiry');

Route::post('/inquiry', 'FrontendController@postInquiry')->name('post_inquiry');

 Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });

app/Ad.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ad extends Model
{
	protected $fillable = [
        'title', 'order', 'avatar', 'redirect_to'
    ];

    public function rules($id = null) {
        return [
            'ad.title' => 'required|max:100|unique:ads,title,'. $id,
            'ad.avatar' => 'image|max:1024' .  (is_null($id) ? '|required' : ''),
            'ad.redirect_to' => 'required',
            'ad.order' => 'required'
        ];
    }
}

app/Http/Controllers/Admin/AdController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Ad;
use App\Service\UploadImage;

class AdController extends Controller
{
    use UploadImage;

    protected $ad;

    public function __construct(Ad $ad) {
        $this->ad = $ad;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ads = Ad::orderBy('order')->get();

        return view('admin.ads.index', compact('ads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.ads.create', ['ad' => $this->ad]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate($this->ad->rules());
        // process store image
        $name = $this->storeImage($request->file('ad.avatar'), 'ads');
        Ad::create([
            'title' => $request->input('ad.title'),
            'avatar' => $name,
            'redirect_to' => $request->input('ad.redirect_to'),
            'order' => $request->input('ad.order')
        ]);
        return redirect()->route('ads.index')->with('alert-success','Ad was created success!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ad = Ad::find($id);
        return view('admin.ads.edit', compact('ad'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate($this->ad->rules($id));
        $ad = Ad::find($id);
        // process store image
        if( $request->hasFile('ad.avatar')) {
            $this->deleteImage($ad->avatar);
            $ad->avatar = $this->storeImage($request->file('ad.avatar'), 'ads');
        }
        //
        $ad->title = $request->input('ad.title');
        $ad->redirect_to = $request->input('ad.redirect_to');
        $ad->order = $request->input('ad.order');
        $ad->save();
        //
        return redirect()->route('ads.index')->with('alert-success','ad was updated success!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ad = Ad::find($id);
        $this->deleteImage($ad->avatar);
        $ad->delete();
        
        return redirect()->route('ads.index')->with('alert-success','Partner was deleted success!');
    }

    public function clear_cache(Request $request) {
        allAds(true);
        return redirect()->route('ads.index')->with('alert-success','Clear cache was created success!');
    }
}

resources/views/admin/ads/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Tao quang cao</h3>
            </div>
            <!-- /.box-header -->
            @include('admin.ads.form')
        </div>
    </div>
</div>
@endsection

resources/views/admin/ads/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Chinh sua quang cao</h3>
            </div>
            <!-- /.box-header -->
            @include('admin.ads.form')
        </div>
    </div>
</div>
@endsection

resources/views/admin/ads/form.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@php($url = is_null($ad->id) ? route('ads.store') : route('ads.update', $ad->id))
<form method="post" action="{{ $url }}" class="form-horizontal" enctype="multipart/form-data">
    <div class="box-body no-padding">
        @csrf
        @if(!is_null($ad->id))
            @method('PATCH')
        @endif
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">ad Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="ad[title]" value="{{ $ad->title ? :old('ad.title') }}"/>
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Avatar</label>
            <div class="col-sm-10">
                <p>Ảnh nên có with=236px, còn heigh thì tùy ý!</p>
                @if (!empty($ad->avatar))
                <img src="{{ asset($ad->avatar) }}"/>
                @endif
                <input type="file" class="form-control" name="ad[avatar]" accept="image/*"/>
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Redirect to</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="ad[redirect_to]" value="{{ $ad->redirect_to ? :old('ad.redirect_to') }}"/>
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Order</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="ad[order]" value="{{ $ad->order ? :old('ad.order') }}"/>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <a href="{{ route('ads.index') }}" class="btn btn-primary pull-left">Cancel</a>
        <button type="submit" class="btn btn-primary pull-right">{{ is_null($ad->id) ? 'Create' : 'Update' }}</button>
    </div>
</form>

resources/views/admin/ads/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
   <div class="col-xs-12">
      <div class="box">
         <div class="box-header">
            <h3 class="box-title">Danh sach quang cao</h3>
            <div class="box-tools">
               <div class="input-group input-group-sm">
                  <a class="label label-success" href="{{route('ads.create')}}">New</a>
                  <a class="label label-success" href="{{ route('ads.clear_cache') }}">Clear Cache</a>
               </div>
            </div>
         </div>
         <!-- /.box-header -->
         <div class="box-body table-responsive no-padding">
            @if (empty($ads))
                Khong co quang cao nao!
            @else
                <table class="table table-hover">
                   <tbody>
                      <tr>
                         <th>ID</th>
                         <th>Title</th>
                         <th>Avatar</th>
                         <th>Redirect to</th>
                         <th>Order</th>
                         <th></th>
                         <th></th>
                      </tr>
                      @foreach($ads as $ad)
                      <tr>
                         <td>{{ $ad->id }}</td>
                         <td>{{ $ad->title }}</td>
                         <td>
                          <img src="{{ asset($ad->avatar) }}" height="100px" width="100px"/>
                         </td>
                         <td>{{ $ad->redirect_to }}</td>
                         <td>{{ $ad->order }}</td>
                         <td>
                             <a class="label label-primary" href="{{ route('ads.edit', $ad->id) }}">Edit</a>
                         </td>
                         <td>
                             <form action="{{ route('ads.destroy', $ad->id) }}" method="post" class="confirmDeleteRecord">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="label label-danger">Delete</button>
                             </form>
                         </td>
                      </tr>
                      @endforeach
                   </tbody>
                </table>
            @endif
         </div>
         <!-- /.box-body -->
      </div>
      <!-- /.box -->
   </div>
</div>
@endsection