routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('frontend_root');

Route::group(['prefix' => 'ql'], function() {
	Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
	//
	Route::post('login', 'Auth\LoginController@login');
});

Route::group(['prefix' => 'ql', 'middleware' => 'auth'], function() {
	
	Route::get('/', 'Admin\AccountController@index')->name('admin_default_root');
	//
	Route::get('logout', 'Auth\LoginController@logout')->name('logout');
	// admin managemening users
	Route::resource('accounts', 'Admin\AccountController');
	// partner
	Route::get('partners/clear_cache', 'Admin\PartnerController@clear_cache')->name('partners.clear_cache');

	Route::resource('partners', 'Admin\PartnerController');

	Route::get('categories/clear_cache', 'Admin\CategoryController@clear_cache')->name('categories.clear_cache');

	Route::resource('categories', 'Admin\CategoryController');
	//
	Route::resource('products', 'Admin\ProductController');

	Route::resource('pages', 'Admin\PageController');

	Route::resource('posts', 'Admin\PostController');

	Route::get('ads/clear_cache', 'Admin\AdController@clear_cache')->name('ads.clear_cache');

	Route::resource('ads', 'Admin\AdController');
	
	Route::get('slides/clear_cache', 'Admin\SlideController@clear_cache')->name('slides.clear_cache');

	Route::resource('slides', 'Admin\SlideController');

	Route::get('setting', 'Admin\SettingController@index')->name('setting.index');

	Route::get('setting/clear_cache', 'Admin\SettingController@clear_cache')->name('setting.clear_cache');

	Route::post('setting', 'Admin\SettingController@store');

	Route::get('inquiry/index', 'Admin\InquiryController@index')->name('inquiry.index');

	Route::post('caches/clear_cache', 'Admin\CacheManagementController@clear_cache')->name('caches.clear_cache');

	Route::get('caches/index', 'Admin\CacheManagementController@index')->name('caches.index');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/product-category/{slug?}', 'FrontendController@category')->name('category_home');

Route::get('/product/{slug}', 'FrontendController@product')->name('product_home');

Route::get('/post-category/{slug}', 'FrontendController@pCategory')->name('post_category_home');

Route::get('/news/{slug}', 'FrontendController@postDetail')->name('post_detail_home');

Route::get('/pages/{slug}', 'FrontendController@pageDetail')->name('page_detail_home');

Route::get('/inquiry', 'FrontendController@getInquiry')->name('get_inquiry');

Route::post('/inquiry', 'FrontendController@postInquiry')->name('post_inquiry');

 Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function rules($id = null) {
        return [
            'user.name' => 'required|max:50|unique:users,name,'. $id,
            'user.email' => 'required|email|unique:users,email,'.$id,
            'user.password' => 'required|confirmed'
        ];
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Create User</h3>
            </div>
            <!-- /.box-header -->
            @include('admin.users.form')
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Edit user</h3>
            </div>
            <!-- /.box-header -->
            @include('admin.users.form')
        </div>
    </div>
</div>
@endsection

resources/views/admin/users/form.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@php($url = is_null($user->id) ? route('accounts.store') : route('accounts.update', $user->id))
<form method="post" action="{{ $url }}" class="form-horizontal">
    <div class="box-body no-padding">
        @csrf
        @if(!is_null($user->id))
            @method('PATCH')
        @endif
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="user[name]" value="{{ $user->name }}"/>
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="user[email]" value="{{ $user->email }}"/>
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Password</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="user[password]"/>
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Password Confirmation</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="user[password_confirmation]"/>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <a href="{{ route('accounts.index') }}" class="btn btn-primary pull-left">Cancel</a>
        <button type="submit" class="btn btn-primary pull-right">{{ is_null($user->id) ? 'Create' : 'Update' }}</button>
    </div>
</form>

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
   <div class="col-xs-12">
      <div class="box">
         <div class="box-header">
            <h3 class="box-title">Users List</h3>
            <div class="box-tools">
               <div class="input-group input-group-sm">
                  <a class="label label-success" href="{{route('accounts.create')}}">New</a>
               </div>
            </div>
         </div>
         <!-- /.box-header -->
         <div class="box-body table-responsive no-padding">
            @if (empty($users))
                Khong co tai khoan nao!
            @else
                <table class="table table-hover">
                   <tbody>
                      <tr>
                         <th>ID</th>
                         <th>UserName</th>
                         <th>Email</th>
                         <th>Created at</th>
                         <th>Action</th>
                         <th></th>
                      </tr>
                      @foreach($users as $user)
                      <tr>
                         <td>{{ $user->id }}</td>
                         <td>{{ $user->name }}</td>
                         <td>{{ $user->email }}</td>
                         <td>{{ $user->created_at }}</td>
                         <td>
                             <a class="label label-primary" href="{{ route('accounts.edit', $user->id) }}">Edit</a>
                         </td>
                         <td>
                             <form action="{{ route('accounts.destroy', $user->id) }}" method="post" class="confirmDeleteRecord">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="label label-danger">Delete</button>
                             </form>
                         </td>
                      </tr>
                      @endforeach
                   </tbody>
                </table>
            @endif
         </div>
         <!-- /.box-body -->
      </div>
      <!-- /.box -->
   </div>
</div>
@endsection