routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontendController@index')->name('frontend_root');

Route::group(['prefix' => 'ql'], function() {
	Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
	//
	Route::post('login', 'Auth\LoginController@login');
});

Route::group(['prefix' => 'ql', 'middleware' => 'auth'], function() {
	
	Route::get('/', 'Admin\AccountController@index')->name('admin_default_root');
	//
	Route::get('logout', 'Auth\LoginController@logout')->name('logout');
	// admin managemening users
	Route::resource('accounts', 'Admin\AccountController');
	// partner
	Route::get('partners/clear_cache', 'Admin\PartnerController@clear_cache')->name('partners.clear_cache');

	Route::resource('partners', 'Admin\PartnerController');

	Route::get('categories/clear_cache', 'Admin\CategoryController@clear_cache')->name('categories.clear_cache');

	Route::resource('categories', 'Admin\CategoryController');
	//
	Route::resource('products', 'Admin\ProductController');

	Route::resource('pages', 'Admin\PageController');

	Route::resource('posts', 'Admin\PostController');

	Route::get('ads/clear_cache', 'Admin\AdController@clear_cache')->name('ads.clear_cache');

	Route::resource('ads', 'Admin\AdController');
	
	Route::get('slides/clear_cache', 'Admin\SlideController@clear_cache')->name('slides.clear_cache');

	Route::resource('slides', 'Admin\SlideController');

	Route::get('setting', 'Admin\SettingController@index')->name('setting.index');

	Route::get('setting/clear_cache', 'Admin\SettingController@clear_cache')->name('setting.clear_cache');

	Route::post('setting', 'Admin\SettingController@store');

	Route::get('inquiry/index', 'Admin\InquiryController@index')->name('inquiry.index');

	Route::post('caches/clear_cache', 'Admin\CacheManagementController@clear_cache')->name('caches.clear_cache');

	Route::get('caches/index', 'Admin\CacheManagementController@index')->name('caches.index');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/product-category/{slug?}', 'FrontendController@category')->name('category_home');

Route::get('/product/{slug}', 'FrontendController@product')->name('product_home');

Route::get('/post-category/{slug}', 'FrontendController@pCategory')->name('post_category_home');

Route::get('/news/{slug}', 'FrontendController@postDetail')->name('post_detail_home');

Route::get('/pages/{slug}', 'FrontendController@pageDetail')->name('page_detail_home');

Route::get('/inquiry', 'FrontendController@getInquiry')->name('get_inquiry');

Route::post('/inquiry', 'FrontendController@postInquiry')->name('post_inquiry');

 Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Category extends Model
{
    use Sluggable;

    protected $fillable = [
        'name', 'order', 'avatar', 'parent_id', 'slug', 'seo_title', 'seo_description'
    ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function rules($id = null) {
        return [
            'category.name' => 'required|max:150|unique:categories,name,'. $id,
            'category.parent_id' => 'required',
            'category.seo_description' => 'max:158',
            'category.seo_title' => 'max:60',
            'category.slug' => 'max:150'
        ];
    }

    public static function treeNav() {
    	$results = [];
    	foreach(Category::orderBy('parent_id')->orderBy('order')->get() as $node) {
    		if ($node->parent_id == 0) {
    			$results[$node->id] = [
					'name' => $node->name,
					'id' => $node->id,
					'parent_id' => $node->parent_id,
                    'slug' => $node->slug,
					'childs' => []
    			];
    			continue;
    		}
    		$results[$node->parent_id]['childs'][$node->id] = [
				'name' => $node->name,
				'id' => $node->id,
				'parent_id' => $node->parent_id,
                'slug' => $node->slug

    		];
    	}
    	return $results;
    }

    public function parent() {
        return $this->hasOne('\App\Category', 'id', 'parent_id');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Category;
use App\Service\UploadImage;

class CategoryController extends Controller
{
    use UploadImage;

    protected $category;

    public function __construct(Category $category) {
        $this->category = $category;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = Category::orderBy('parent_id')->orderBy('order');
        if ($request->input('cname')) {
            $categories = $categories->where('name', 'like', $request->input('cname').'%');
        }
        if ($request->input('cparent_id')) {
            $categories = $categories->where('cparent_id', $request->input('cparent_id'));
        }
        $categories = $categories->get();

        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create', ['category' => $this->category]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate($this->category->rules());
        // process store image
        //$name = $this->storeImage($request->file('category.avatar'), 'category');
        Category::create($request->input('category'));
        return redirect()->route('categories.index')->with('alert-success','category was created success!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate($this->category->rules($id));
        $category = Category::find($id);
        //
        $category->name = $request->input('category.name');
        $category->seo_title = $request->input('category.seo_title');
        $category->seo_description = $request->input('category.seo_description');
        $category->slug = $request->input('category.slug');
        $category->parent_id = $request->input('category.parent_id');
        $category->order = $request->input('category.order');
        $category->save();
        //
        return redirect()->route('categories.index')->with('alert-success','category was updated success!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        if($category->parent_id != 0) {
            $category->delete();
        }
        
        return redirect()->route('categories.index')->with('alert-success','category was deleted success!');
    }

    public function clear_cache() {
        treeNav(true);
        return redirect()->route('categories.index')->with('alert-success','Clear cache was created success!');
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Create Category</h3>
            </div>
            <!-- /.box-header -->
            @include('admin.categories.form')
        </div>
    </div>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Edit Category</h3>
            </div>
            <!-- /.box-header -->
            @include('admin.categories.form')
        </div>
    </div>
</div>
@endsection

resources/views/admin/categories/form.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@php($url = is_null($category->id) ? route('categories.store') : route('categories.update', $category->id))
<form method="post" action="{{ $url }}" class="form-horizontal" enctype="multipart/form-data">
    <div class="box-body no-padding">
        @csrf
        @if(!is_null($category->id))
            @method('PATCH')
        @endif
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="category[name]" value="{{ $category->name ?? old('category.name') }}"/>
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Slug</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="category[slug]" value="{{ $category->slug ?? old('category.slug') }}"/>
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Parent_id</label>
            <div class="col-sm-10">
                <select name="category[parent_id]">
                    @if ($category->parent_id == 0 && $category->id)
                    <option value="0">Root(Level 1)</option>
                    @else
                        @foreach(categoriesWithLevel() as $cate_root)
                            <option value="{{ $cate_root->id }}" {{$cate_root->id == $category->parent_id ? 'selected="selected"' : ''}}>{{ $cate_root->name }}</option>
                        @endforeach
                    @endif
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="title" class="col-sm-2 control-label">Thứ tự hiển thị(0..10)</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="category[order]" value="{{ $category->order }}"/>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <a href="{{ route('categories.index') }}" class="btn btn-primary pull-left">Cancel</a>
        <button type="submit" class="btn btn-primary pull-right">{{ is_null($category->id) ? 'Create' : 'Update' }}</button>
    </div>
</form>

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="row">
   <div class="col-xs-12">
      <div class="box">
         <div class="box-header">
            <h3 class="box-title">Danh sach danh mục sản phẩm</h3>
            <div class="box-tools">
               <div class="input-group input-group-sm">
                  <a class="label label-success" href="{{route('categories.create')}}">New</a>
                  <a class="label label-success" href="{{ route('categories.clear_cache') }}">Clear Cache</a>
               </div>
            </div>
         </div>
         <!-- /.box-header -->
         <div class="box-body table-responsive no-padding">
            @if (empty($categories))
                Khong co tai danh muc nao!
            @else
                <table class="table table-hover">
                   <tbody>
                      <tr>
                         <th>ID</th>
                         <th>Name</th>
                         <th>Parent</th>
                         <th>Slug</th>
                         <th>Order</th>
                         <th></th>
                         <th></th>
                      </tr>
                      @foreach($categories as $category)
                      <tr>
                         <td>{{ $category->id }}</td>
                         <td>{{ $category->name }}</td>
                         <td>
                          @if (!empty($category->parent))
                          {{ $category->parent->name }}
                          @else
                           Root(Level 1)
                          @endif
                         </td>
                         <td>{{ $category->slug }}</td>
                         <td>{{ $category->order }}</td>
                         <td>
                             <a class="label label-primary" href="{{ route('categories.edit', $category->id) }}">Edit</a>
                         </td>
                         <td>
                             <form action="{{ route('categories.destroy', $category->id) }}" method="post" class="confirmDeleteRecord">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="label label-danger">Delete</button>
                             </form>
                         </td>
                      </tr>
                      @endforeach
                   </tbody>
                </table>
            @endif
         </div>
         <!-- /.box-body -->
      </div>
      <!-- /.box -->
   </div>
</div>
@endsection